'use client'

import { CircleDollarSign, Layers, TrendingUp } from 'lucide-react'
import { SectionHeading } from '@/components/shared/SectionHeading'
import {
  REFERRAL_DISPLAY_INVESTMENT_COMMISSION,
  REFERRAL_DISPLAY_MAX_WEEKLY_SHARE,
  REFERRAL_DISPLAY_PROFIT_SHARE,
  REFERRAL_DISPLAY_PROFIT_SHARE_SUMMARY,
  REFERRAL_EARNINGS_EXAMPLES,
} from '@/lib/referral/display-config'
import { formatCurrency } from '@/lib/data/format'
import { cn } from '@/lib/utils'

const cardClass =
  'group relative overflow-hidden rounded-2xl border border-gray-200 bg-white p-5 shadow-sm transition-shadow hover:shadow-md sm:p-6'

export function ReferralCommissionSection() {
  return (
    <section aria-label="Commission structure" className="space-y-3">
      <SectionHeading>How you earn</SectionHeading>

      <div className="grid grid-cols-1 gap-4 lg:grid-cols-3">
        <article className={cn(cardClass, 'border-orange-200/60 bg-gradient-to-br from-orange-50/50 to-white')}>
          <div className="flex h-11 w-11 items-center justify-center rounded-xl bg-orange-100 text-orange-600">
            <CircleDollarSign className="h-5 w-5" aria-hidden="true" />
          </div>
          <h3 className="mt-4 text-lg font-bold text-gray-900">Investment Commission</h3>
          <p className="mt-1 text-3xl font-bold tracking-tight text-orange-600">
            {REFERRAL_DISPLAY_INVESTMENT_COMMISSION}
          </p>
          <p className="mt-2 text-sm font-medium text-gray-700">One-time commission</p>
          <p className="mt-3 text-sm leading-relaxed text-gray-600">
            Earn when a referred investor makes their qualifying first investment or deposit. Paid once
            per referred member — transparent and tracked in your wallet.
          </p>
          <div className="mt-4 rounded-xl border border-orange-100 bg-white/80 px-4 py-3">
            <p className="text-[11px] font-semibold uppercase tracking-wide text-gray-500">Example</p>
            <p className="mt-1 text-sm text-gray-700">{REFERRAL_EARNINGS_EXAMPLES.investmentCommission.label}</p>
            <p className="mt-1 text-base font-bold text-emerald-600">
              You earn {formatCurrency(REFERRAL_EARNINGS_EXAMPLES.investmentCommission.commission)}
            </p>
          </div>
        </article>

        <article className={cn(cardClass, 'border-[#0052ff]/20 bg-gradient-to-br from-blue-50/40 to-white lg:col-span-1')}>
          <div className="flex h-11 w-11 items-center justify-center rounded-xl bg-[#0052ff]/10 text-[#0052ff]">
            <TrendingUp className="h-5 w-5" aria-hidden="true" />
          </div>
          <h3 className="mt-4 text-lg font-bold text-gray-900">Weekly Profit Share</h3>
          <p className="mt-1 text-sm font-medium text-gray-700">
            Up to {REFERRAL_DISPLAY_MAX_WEEKLY_SHARE} on downline profits, every week
          </p>
          <p className="mt-3 text-sm leading-relaxed text-gray-600">
            Receive a share of verified weekly profits generated by investors in your network — across
            four levels, with no recruitment fees or hidden tiers.
          </p>
          <ul className="mt-4 space-y-2">
            {REFERRAL_DISPLAY_PROFIT_SHARE.map((row) => (
              <li
                key={row.level}
                className="flex items-center justify-between rounded-lg border border-gray-100 bg-gray-50/80 px-3 py-2.5"
              >
                <span className="text-sm font-semibold text-gray-800">Level {row.level}</span>
                <span className="rounded-full bg-[#0052ff]/10 px-2.5 py-0.5 text-sm font-bold text-[#0052ff]">
                  {row.rate}
                </span>
              </li>
            ))}
          </ul>
          <div className="mt-4 rounded-xl border border-blue-100 bg-white/80 px-4 py-3">
            <p className="text-[11px] font-semibold uppercase tracking-wide text-gray-500">Example</p>
            <p className="mt-1 text-sm text-gray-700">{REFERRAL_EARNINGS_EXAMPLES.weeklyProfitShare.label}</p>
            <p className="mt-1 text-base font-bold text-emerald-600">
              Your L1 share: {formatCurrency(REFERRAL_EARNINGS_EXAMPLES.weeklyProfitShare.level1Earning)}/week
            </p>
          </div>
        </article>

        <article className={cn(cardClass, 'border-emerald-200/60 bg-gradient-to-br from-emerald-50/40 to-white')}>
          <div className="flex h-11 w-11 items-center justify-center rounded-xl bg-emerald-100 text-emerald-600">
            <Layers className="h-5 w-5" aria-hidden="true" />
          </div>
          <h3 className="mt-4 text-lg font-bold text-gray-900">4-Level Network</h3>
          <p className="mt-2 text-sm leading-relaxed text-gray-600">
            Build depth responsibly. Your network extends four levels — each with its own profit-share
            rate, visible in your referral tree and analytics.
          </p>
          <p className="mt-4 rounded-xl bg-emerald-50/80 px-4 py-3 text-sm font-semibold text-emerald-800">
            {REFERRAL_DISPLAY_PROFIT_SHARE_SUMMARY}
          </p>
          <ul className="mt-4 space-y-2 text-sm text-gray-600">
            <li className="flex gap-2">
              <span className="text-emerald-600" aria-hidden="true">
                ✓
              </span>
              Real investment activity required for payouts
            </li>
            <li className="flex gap-2">
              <span className="text-emerald-600" aria-hidden="true">
                ✓
              </span>
              Referred investors always own their funds
            </li>
            <li className="flex gap-2">
              <span className="text-emerald-600" aria-hidden="true">
                ✓
              </span>
              Not a membership or recruitment fee model
            </li>
          </ul>
        </article>
      </div>
    </section>
  )
}
